type User {
  id: Int
  nome: String
  email: String
  telefone: String
  perfil: Perfil
}

input UsuarioInput {
  id: Int
  nome: String
  email: String
  telefone: String
}

type Query {
  usuario(id: Int): User
  users: [User]
}

type Mutation {
  criarUsuario(data: UsuarioInput): User!
  atualizarUsuario(id: Int, data: UsuarioInput): User!
}
